### ISSUE TITLE
Geração de referências

### ISSUE THREAD

**Issue by leonardodecuritiba** [wmeira/utfprct-tex#2]
William, clonei o repositório, instalei o texstudio, e todos os pacotes necessário, mas ao tentar gerar uma referência, ele fica com **??** marcado. 
Pode me ajudar nessa questão?

Log:
_Processo iniciado: pdflatex -synctex=1 -interaction=nonstopmode "utfprct".tex

This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support). Scanning input file utfprct.idx....

done (79 entries accepted, 0 rejected). Sorting entries....done (522 comparisons). Generating output file utfprct.ind....done (64 lines written, 0 warnings). Output written in utfprct.ind. Transcript written in utfprct.ilg.

This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support). Scanning style file ./utfprct.ist...................

..........done (29 attributes redefined, 0 ignored). Scanning input file utfprct.glo....done (73 entries accepted, 0 rejected). Sorting entries....done (471 comparisons). Generating output file utfprct.gls....done (50 lines written, 0 warnings). Output written in utfprct.gls. Transcript written in utfprct.glg.

This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support). Scanning style file ./utfprct.ist........................

.....done (29 attributes redefined, 0 ignored). Scanning input file utfprct.acn....done (1 entries accepted, 0 rejected). Sorting entries...done (0 comparisons). Generating output file utfprct.acr....done (6 lines written, 0 warnings). Output written in utfprct.acr. Transcript written in utfprct.alg.

This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support). Scanning style file ./utfprct.ist.............................done (29 attributes redefined, 0 ignored). Scanning input file utfprct.acn2....

done (16 entries accepted, 0 rejected). Sorting entries....done (71 comparisons). Generating output file utfprct.acr2....done (20 lines written, 0 warnings). Output written in utfprct.acr2. Transcript written in utfprct.alg2.

This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support). Scanning style file ./utfprct.ist...................

..........done (29 attributes redefined, 0 ignored). Scanning input file utfprct.acn3....done (3 entries accepted, 0 rejected). Sorting entries....done (4 comparisons). Generating output file utfprct.acr3....done (12 lines written, 0 warnings). Output written in utfprct.acr3. Transcript written in utfprct.alg3.

This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support). Scanning style file /usr/share/texlive/texmf-dist/makeindex/nomencl/nomencl.ist............

done (12 attributes redefined, 3 ignored). Scanning input file utfprct.nlo....done (25 entries accepted, 0 rejected). Sorting entries....done (101 comparisons). Generating output file utfprct.nls....done (39 lines written, 0 warnings). Output written in utfprct.nls. Transcript written in utfprct.ilg.

O processo saiu normalmente
_

**Comment by wmeira** [comment]
Boa noite, Leonardo

Vc está tentando compilar o arquivo de exemplo ou já realizou alguma modificação no bib?

**Comment by leonardodecuritiba** [comment]
O arquivo de exemplo mesmo. Não modifiquei nada, ambiente: Ubuntu

**Comment by wmeira** [comment]
Reproduzi o erro aqui no TexStudio

Por default, o TexStudio não parece estar compilando o Bibtex e fazendo o procedimento completo de compilação

Tem que rodar: 
pdflatex -> bibtex -> pdflatex -> pdflatex

Segue os passos para compilar o arquivo completo no TexStudio:

1) Opções -> Configurar TexStudio -> Compilação -> Compilador predefinido -> "clica na ferramenta pra editar" 
2) Adicione os comandos na seguinte ordem (ver imagem)

![image](https://user-images.githubusercontent.com/793297/91505312-adb83580-e8a5-11ea-8e09-6daef2f60a69.png)

Qualquer coisa, me avisa!

**Comment by leonardodecuritiba** [comment]
Show! Deu certo.
Vou abrir outro card para outra situação que encontrei.
