### ISSUE TITLE
Nome do curso

### ISSUE THREAD

**Issue by leonardodecuritiba** [wmeira/utfprct-tex#3]
Uma sugestão.

Em diversos pontos do arquivo **utfprct-dados.tex** identifiquei que há uma instrução: **\imprimircurso**, porém neste mesmo arquivo, não encontrei onde definir o nome do curso. Aí reparei que no arquivo _utfprct.cls_ tem as linhas:
`%% Nome do curso
\providecommand{\imprimircurso}{Nome do Curso}
\newcommand{\Curso}[1]{\renewcommand{\imprimircurso}{#1}}`

então deduzi que eu deveria usar o comando **\Curso** no arquivo **utfprct-dados.tex**. Mas isso foi uma dedução. 
Sugiro, colocar nesse arquivo um exemplo de como definir o nome do curso, e seguir o padrão que você seguiu.

**Comment by wmeira** [comment]
Opa, Leonardo

Obrigado por reparar. Acidentalmente, eu removi os comandos \Departamento \Curso e \Course do utfprct-dados.tex no último commit

Atualizei a versão!
Obrigado, novamente!

**Comment by leonardodecuritiba** [comment]
Eu é quem agradeço! Sucesso!
