### ISSUE TITLE
Alteração de documento para inglês

### ISSUE THREAD

**Issue by rsromanus** [wmeira/utfprct-tex#4]
Boa noite,

Estou tendo problemas em adaptar o documento para inglês, por mais que mude no cls para Table no lugar de Tabela, no List of tables o nome ainda aparece como Tabela 1... O mesmo acontece para as figuras que persistem com o nome Figura 1. Peço que se possível, me auxilie com relação a esse aspecto.

Agradeço desde já,

**Comment by wmeira** [comment]
Boa noite, rsromanus

Para adaptar o texto para o inglês é só alterar a ordem em que os idiomas aparecem no \documentclass, colocando english após brazil, conforme figura abaixo. Todos os textos gerados automaticamente serão alterados para inglês, incluindo a lista de tabela e lista de figuras.

![image](https://user-images.githubusercontent.com/793297/99739132-d584f700-2aaa-11eb-8636-30cbc5f8699c.png)

Qualquer coisa só falar.

**Comment by rsromanus** [comment]
Agora deu certo. Eu estava deixando os dois campos como english ao invés de inverter somente e por isso estava dando errado.

Muito obrigado!
