### ISSUE TITLE
Arquivo bibtex

### ISSUE THREAD

**Issue by cassioalmeidas** [wmeira/utfprct-tex#5]
Como usar com arquivo o bibtex ?

**Comment by wmeira** [comment]
Olá, Cassio

Só colocar o nome do seu arquivo .bib aqui nessa parte do utfprct.tex

![image](https://user-images.githubusercontent.com/793297/108600598-bda56380-7376-11eb-8fe6-d1a3057149e2.png)


Att,
William Meira
