### ISSUE TITLE
Título em inglês na folha de rosto

### ISSUE THREAD

**Issue by Minoro** [wmeira/utfprct-tex#6]
Estou com problemas para exibir o título do trabalho em inglês na folha de rosto. No documento em PDF está sendo exibido apenas o título em português. No arquivo `utfprct-dados.txt` defini as variáveis da seguinte forma:
```latex
\TituloDoDocumento{%%
Detecção de fogo ativo por aprendizado profundo em imagens provenientes do satélite Landsat-8 
}%

%% Título do trabalho em INGLÊS (abstract)
\DocumentTitle{%%
Active fire detection with Deep-Learning in Landsat-8 imagery
}%

% [...]

\TituloEmMultiplasLinhas{%%
Detecção de fogo ativo por aprendizado \par
profundo em imagens provenientes do satélite Landsat-8 
}%

\TituloEmMultiplasLinhasIngles{%%
Active fire detection with Deep-Learning \par
in Landsat-8 imagery
}%
```

E no documento `utfprct.txt` os idiomas estão na seguinte ordem:
```latex
english,%% Idioma adicional para hifenização  (colocar em último para doc. em inglês)  
brazil%% Idioma principal do documento (último da lista)   
```
e o início do documento está da seguinte forma:
```latex
\begin{document}%% Não comente esta linha

\pretextual%% Não comente esta linha

\incluircapa%% Comente para remover este item

\Licenca{CC-BY}
%\incluirfolhaderosto*%% Com ficha catalográfica no verso 
\incluirfolhaderosto%% Sem ficha catalográfica no verso
```

Alguma ideia do que pode estar acontecendo?

**Comment by wmeira** [comment]
Opa, Minoro

Com essas configurações, eu obtive o seguinte resultado: 

![image](https://user-images.githubusercontent.com/793297/141375782-2121355b-f6e2-4def-9bd5-b1c7f3b9b4e7.png)


Acabei comentando também a ficha catalográfica: 
%\incluirfichacatalografica{./PreTexto/ficha_catalografica_exemplo.pdf}%%1

Mantive o seguinte documentclass (default)

%% Classe e opções de documento
\documentclass[%% Opções
%% -- Opções da classe MEMOIR --
  12pt,%% Tamanho da fonte: 10pt, 11pt, 12pt, etc.
  a4paper,%% Tamanho do papel: a4paper (A4), letterpaper (carta), etc.
  % fleqn,%% Alinhamento das equações à esquerda (comente para alinhamento centralizado)
  % leqno,%% Numeração das equações no lado esquerdo (comente para lado direito)
  oneside,%% IMPRESSÃO dos elementos textuais e pós-textuais: oneside (apenas no anverso) ou twoside (anverso e verso, se mais de 100 p.) (insere páginas em branco).
%%  
%% -- Opções da classe ABNTEX2 --
  sumario = abnt-6027-2012,%% Formatação do sumário: tradicional (estilo tradicional) ou abnt-6027-2012 (norma ABNT 6027-2012)
  chapter = TITLE,%% Títulos de capítulos em maiúsculas (comente para desabilitar)
  section = TITLE,%% Títulos de seções secundárias em maiúsculas (comente para desabilitar)
  % subsection = TITLE,%% Títulos de seções terciárias em maiúsculas (comente para desabilitar)
  % subsubsection = TITLE,%% Títulos de seções quartenárias em maiúsculas (comente para desabilitar)
%%  
%% -- Opções da classe UTFPRCT-TEX --
  pretextualoneside,%% Impressão dos elementos pré-textuais: pretextualoneside (anverso) ou pretextualtwoside (anverso e verso)
  fontetimes,%% Fonte do texto: fontetimes (times), fontearial (arial) ou fontecourier (courier), fontemodern (lmodern - default latex). Times and Arial are ABNT recommended
   %vinculoscoloridos,%% Cores nos vínculos (citações, arquivos, links, url, etc.) (comente para desabilitar). NBR 14724/2011: cor preta (inclusive hyperlinks)
  semrecuonosumario,%% Remoção do recuo dos itens no sumário (comente para adição do recuo, se estilo tradicional)
  %inserirbackref,%% Inserir backref na lista de referências (e.g., Citado na página...)
  usemakeindex,%% Compilação de glossários e índices utilizando makeindex (comente para desabilitar)
  legendascentralizadas,%% Alinhamento das legendas centralizado (comente para alinhamento à esquerda)
%%  
%% -- Opções da folha de aprovação -- 
%% O mais comum é anexar o PDF do termo de aprovação sem assinaturas. As opções abaixo são para o formato da pós-graduação UTFPR-PG (Ponta Grossa) e podem servir de placeholder para este template.
  %aprovacaoestiloppg,%% Folha de aprovação do programa de pós-graduação no estilo do PPG (comente para estilo padrão)
  %pardeassinaturas,%% Assinaturas na folha de aprovação em até duas colunas (comente para em uma única coluna)
  % linhasdeassinaturas,%% Linhas de assinaturas na folha de aprovação (comente para remover as linhas)
%%  
%% -- Opções do pacote babel (hifenização) -- % 
  %french,%% Idioma adicional para hifenização (suporte parcial)
  %spanish,%% Idioma adicional para hifenização (suporte parcial)
  english,%% Idioma adicional para hifenização  (colocar em último para doc. em inglês)  
  brazil%% Idioma principal do documento (último da lista) 
]{utfprct}%% Classe utfprct


Talvez possa ter sido alterada no CLS que preenche ambos os títulos (1246-1254):

\ifthenelse{\equal{\lingua}{english}} {
    	\vspace{-45pt}
		{\large\MakeUppercase{\imprimirtituloemmultiplaslinhasingles}}\\[10pt]%% Título do documento (em ingles)
		{\large{\imprimirtituloemmultiplaslinhas}}\\[35pt]
    }{
    	\vspace{-45pt}
		{\large\MakeUppercase{\imprimirtituloemmultiplaslinhas}}\\[10pt]%% Título do documento
		{\large{\imprimirtituloemmultiplaslinhasingles}}\\[35pt]
    } 


Att, 
wmeira

**Comment by Minoro** [comment]
Substitui o meu arquivo `utfprct.cls` pela versão do repositório e funcionou.
Obrigado.
